POST http://localhost:3333
Content-Type: application/json

{
    "title": "livro teste",
    "sinopse": "Este é o primeiro livro de Node.js com MySQL",
    "numero_de_paginas": 900
}


GET http://localhost:3333



PUT http://localhost:3333/b9bfb29f-7981-474c-b989-a293c0c341a5
Content-Type: application/json

{
    "title": "alterei este livro",
    "sinopse": "sinopse atualizada",
    "numero_de_paginas": 345
}






